androiddev, django, express, angular
sreejithdikru/TinkerHub-Learning-Paths pull request #11
Opened 2021-08-06 18:29 UTC by rosetanya898

2021-08-06 18:54 UTC, irenekurien requested changes

2021-08-06 18:54 UTC, irenekurien commented on content/angular/index.md
> +- [Angular - The Complete Guide (2021 Edition)](https://www.udemy.com/)
Please add the correct link to udemy.

2021-08-06 18:54 UTC, irenekurien commented on content/django-path/index.md
> +- [Python Django - The Practical Guide](https://www.udemy.com/)
Please check and add the correct link

2021-08-06 18:54 UTC, irenekurien commented on content/dsa/index.md
> +- [Udemy](https://www.udemy.com/)
Please check the link here also.

2021-08-07 06:51 UTC, rosetanya898 reviewed
Modified links

2021-08-07 12:07 UTC, merged